server:
  port: 9770

spring:
  application:
    name: gateway-application
  profiles:
    active: local
  cloud:
    gateway:
      httpclient:
        responseTimeout: 30000
        connectTimeout: 20000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true